version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27018:27018
    volumes:
      - mongodb_data_container:/data/db
  twitterapp:
    image: paulrognon/bigdataubmongodb
    command: python Twitter_mongodb.py
    depends_on:
      - mongodb
    ports:
      - 5001:5001
    volumes:
      - ./twitter-app:/opt/twitter-app
volumes:
    mongodb_data_container:
      driver: local
